const { Client } = require("@notionhq/client");
require('dotenv').config();

// Initialize the connection using your .env keys
const notion = new Client({ auth: process.env.NOTION_TOKEN });
const PAGE_ID = process.env.NOTION_PAGE_ID;

async function addEntryToNotion(title, body) {
    try {
        console.log("Attempting to connect to Notion...");
        await notion.blocks.children.append({
            block_id: PAGE_ID,
            children: [
                {
                    object: 'block',
                    type: 'heading_2',
                    heading_2: { rich_text: [{ type: 'text', text: { content: title } }] }
                },
                {
                    object: 'block',
                    type: 'paragraph',
                    paragraph: { rich_text: [{ type: 'text', text: { content: body } }] }
                }
            ],
        });
        console.log("🚀 SUCCESS! Check your Notion page right now!");
    } catch (err) {
        console.error("❌ Notion Connection Failed:", err.body || err);
    }
}

// THIS IS A SELF-TEST: Running this file directly will execute this block
if (require.main === module) {
    addEntryToNotion(
        "🔄 Live Pipeline Test",
        "This entry was automatically generated by the backend server framework via the Notion REST API."
    );
}

module.exports = { addEntryToNotion };